### ISSUE TITLE
(R) where should we store zipped versions? (blocking #707)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#678] opened 2018-04-16 20:29 UTC
When we create zips, we probably want to keep a copy of each version of each druid locally?  (remember local POSIX impl. of endpoint?)   So where should these files be stored?

- in moab??? 
- near moab???
- somewhere else??

amount of storage need is significant;  Julian seemed to talk of a big storage place for these earlier??

so do we do druid tree to zips on "other" storage?   Room to grow?  Etc.  (Is this our POSIX archival location?)

**Comment by SaravShah** [comment] 2018-04-24 16:57
```
Julian Morley [11:09 AM]
Yeah, there's an sdr_transfers vol.
```

**Comment by SaravShah** [comment] 2018-04-24 16:57
Julian Morley [12:26 PM]
OK, we're not going to store zips long term here. It's only for temporary transfer space.
And also renaming NFS vols is a PITA.
The Mythical 4th SDR Copy (which may well be an S3-compatible object store of zips) is completely separate from sdr_transfers. Which is just for transfering stuff from local storage to cloud storage, with some transitory caching of content to reduce duplicate work.

And @azanella, no, no stage-specific volume. Just _do it live_.
( nothing can go wrong! )

**Comment by jmartin-sul** [comment] 2018-05-01 19:36
closing #706 as a dupe of this, the relevant info and questions from that issue that aren't already capture here are:


- pres cat config tells you path to the mount (settings.yml)

- What needs what access? (read/write) (in the mount)
  - zip maker worker definetely needs read/write
  - endpoint upload worker definitely needs read access.  if endpoint worker does a touch to indicate recent usage of a zip, it may need write access too.

- this corresponds to the cylinder in the middle of the diagram.

https://www.lucidchart.com/documents/view/45ded815-9fec-46fa-b935-1e26f3819f0e/0

**Comment by ndushay** [comment] 2018-05-08 01:34
duplicate of #738, #739?

**Comment by jmartin-sul** [comment] 2018-05-08 15:47
yup, closing

**Closed by jmartin-sul** 2018-05-08 15:47 UTC
Labels: blocking!, high priority, question, ready, replication
