### ISSUE TITLE
(SPC) retrofit workflow reporting to seeding code (blocked by #404)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#441] opened 2017-12-21 21:27 UTC
On the assumption that we are not done running seeding, we should ensure that errors encountered during seeding are reported to worklflows.

**Comment by jmartin-sul** [comment] 2018-01-18 19:27
dupe of #466?  seems done.

**Closed by jmartin-sul** 2018-01-18 19:27 UTC
Labels: blocked, ready
