### ISSUE TITLE
(R) Which ZIP lib to use?

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#737] opened 2018-05-07 23:26 UTC
Should we use Zlib, rubyzip, or shell out?

Story Time Notes:
https://docs.google.com/document/d/10HMhTMWlZaM1DJChFr2r3coOVDZKe0EDAH8PPumb-2E/edit#

**Comment by atz** [comment] 2018-05-11 21:09
According to notes, previous rough implementation used:
```
zip -v0r -s 10g
```
Some reading:
- https://wiki.debian.org/ReproducibleBuilds/Howto
- https://content.pivotal.io/blog/barriers-to-deterministic-reproducible-zip-files 
- Notes about our intended structure [here](https://docs.google.com/document/d/1ofCfmeZ_lx8cpMUFbCb1Bt2R3TSna48oPuQT8YphSvg/edit#heading=h.y9oczez8cqg3)

Takeaway:
- We should also use `-X` or equivalent to avoid putting access-timestamps in the zip

**Comment by atz** [comment] 2018-05-11 22:29
My local zip:
```
 zip -v
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
Currently maintained by E. Gordon.  Please send bug reports to
the authors using the web page at www.info-zip.org; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip,
as of above date; see http://www.info-zip.org/ for other sites.

Compiled with gcc 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34) for Unix (Mac OS X) on Oct 14 2016.

Zip special compilation options:
	USE_EF_UT_TIME       (store Universal Time)
	SYMLINK_SUPPORT      (symbolic links supported)
	LARGE_FILE_SUPPORT   (can read and write large files on file system)
	ZIP64_SUPPORT        (use Zip64 to store large files in archives)
	STORE_UNIX_UIDs_GIDs (store UID/GID sizes/values using new extra field)
	UIDGID_16BIT         (old Unix 16-bit UID/GID extra field also used)
	[encryption, version 2.91 of 05 Jan 2007] (modified for Zip 3)
```

Point being `zip` is a decade old and that *is* the most recent release.  While that might seem like a drawback, in this case it suggests incredible stability.  Compare to [`rubyzip`](https://github.com/rubyzip/rubyzip), which has 19 releases in the same period.

**Comment by atz** [comment] 2018-05-11 22:48
Using:
```sh
pushd spec/fixtures/storage_root01/moab_storage_trunk/jj/925/bx/9565/
zip -vr0X -s 10g jj925bx9565.v0001.zip jj925bx9565/v0001
popd
```
I get a file w/ MD5 of `ee81a6ab6710ead47aeb28e8f750fdda` like:
```sh
$ unzip -lv spec/fixtures/storage_root01/moab_storage_trunk/jj/925/bx/9565/jj925bx9565.v0001.zip
Archive:  spec/fixtures/storage_root01/moab_storage_trunk/jj/925/bx/9565/jj925bx9565.v0001.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 04-20-2018 12:06 00000000  jj925bx9565/v0001/
       0  Stored        0   0% 04-20-2018 12:06 00000000  jj925bx9565/v0001/data/
       0  Stored        0   0% 04-20-2018 12:06 00000000  jj925bx9565/v0001/data/content/
 6508496  Stored  6508496   0% 04-20-2018 12:06 ac341bd4  jj925bx9565/v0001/data/content/PC0170_s3_4th_of_July_2010-07-04_095432_0003.jpg
       0  Stored        0   0% 04-20-2018 12:06 00000000  jj925bx9565/v0001/data/metadata/
     873  Stored      873   0% 04-20-2018 12:06 960c6665  jj925bx9565/v0001/data/metadata/contentMetadata.xml
     345  Stored      345   0% 04-20-2018 12:06 be89e932  jj925bx9565/v0001/data/metadata/descMetadata.xml
     645  Stored      645   0% 04-20-2018 12:06 8d12b9d6  jj925bx9565/v0001/data/metadata/identityMetadata.xml
     263  Stored      263   0% 04-20-2018 12:06 7d1a7d24  jj925bx9565/v0001/data/metadata/provenanceMetadata.xml
     721  Stored      721   0% 04-20-2018 12:06 d0610866  jj925bx9565/v0001/data/metadata/relationshipMetadata.xml
     684  Stored      684   0% 04-20-2018 12:06 c07d0016  jj925bx9565/v0001/data/metadata/rightsMetadata.xml
    4490  Stored     4490   0% 04-20-2018 12:06 58e11294  jj925bx9565/v0001/data/metadata/technicalMetadata.xml
     134  Stored      134   0% 04-20-2018 12:06 72983849  jj925bx9565/v0001/data/metadata/versionMetadata.xml
    4133  Stored     4133   0% 04-20-2018 12:06 ce5990ca  jj925bx9565/v0001/data/metadata/workflows.xml
       0  Stored        0   0% 04-20-2018 12:06 00000000  jj925bx9565/v0001/manifests/
    4125  Stored     4125   0% 04-20-2018 12:06 22fd4501  jj925bx9565/v0001/manifests/fileInventoryDifference.xml
    1614  Stored     1614   0% 04-20-2018 12:06 44d2eaf3  jj925bx9565/v0001/manifests/manifestInventory.xml
    3118  Stored     3118   0% 04-20-2018 12:06 17bf12ff  jj925bx9565/v0001/manifests/signatureCatalog.xml
    3455  Stored     3455   0% 04-20-2018 12:06 c79865fb  jj925bx9565/v0001/manifests/versionAdditions.xml
    3527  Stored     3527   0% 04-20-2018 12:06 7e525d93  jj925bx9565/v0001/manifests/versionInventory.xml
--------          -------  ---                            -------
 6536623          6536623   0%                            20 files

```

Given the combination of default options documented above and the CLI opts passed to the command, I believe this is the desired output.  Attempting to reproduce via `rubyzip`.

**Comment by tallenaz** [comment] 2018-05-11 23:30
So, similar to `ls`, `zip` isn't broken 👍

**Comment by atz** [comment] 2018-05-12 00:08
Using `rubyzip` code I drafted in a [branch](https://github.com/sul-dlss/preservation_catalog/blob/zip_evaluation/lib/zipper.rb) including:

```
  Zip.setup do |c|
    c.unicode_names = true
    c.default_compression = Zlib::NO_COMPRESSION
    c.write_zip64_support = true
  end
```
I still cannot get the desired output:
```
unzip -lv rubyzip.zip 
Archive:  rubyzip.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 05-11-2018 16:32 00000000  jj925bx9565/v0001/
       0  Stored        0   0% 05-11-2018 16:32 00000000  jj925bx9565/v0001/data/
       0  Stored        0   0% 05-11-2018 16:32 00000000  jj925bx9565/v0001/data/content/
 6508496  Defl:N  6509486   0% 05-11-2018 16:32 ac341bd4  jj925bx9565/v0001/data/content/PC0170_s3_4th_of_July_2010-07-04_095432_0003.jpg
       0  Stored        0   0% 05-11-2018 16:32 00000000  jj925bx9565/v0001/data/metadata/
     873  Defl:N      878  -1% 05-11-2018 16:32 960c6665  jj925bx9565/v0001/data/metadata/contentMetadata.xml
     345  Defl:N      350  -1% 05-11-2018 16:32 be89e932  jj925bx9565/v0001/data/metadata/descMetadata.xml
     645  Defl:N      650  -1% 05-11-2018 16:32 8d12b9d6  jj925bx9565/v0001/data/metadata/identityMetadata.xml
     263  Defl:N      268  -2% 05-11-2018 16:32 7d1a7d24  jj925bx9565/v0001/data/metadata/provenanceMetadata.xml
     721  Defl:N      726  -1% 05-11-2018 16:32 d0610866  jj925bx9565/v0001/data/metadata/relationshipMetadata.xml
     684  Defl:N      689  -1% 05-11-2018 16:32 c07d0016  jj925bx9565/v0001/data/metadata/rightsMetadata.xml
    4490  Defl:N     4495  -0% 05-11-2018 16:32 58e11294  jj925bx9565/v0001/data/metadata/technicalMetadata.xml
     134  Defl:N      139  -4% 05-11-2018 16:32 72983849  jj925bx9565/v0001/data/metadata/versionMetadata.xml
    4133  Defl:N     4138  -0% 05-11-2018 16:32 ce5990ca  jj925bx9565/v0001/data/metadata/workflows.xml
       0  Stored        0   0% 05-11-2018 16:32 00000000  jj925bx9565/v0001/manifests/
    4125  Defl:N     4130  -0% 05-11-2018 16:32 22fd4501  jj925bx9565/v0001/manifests/fileInventoryDifference.xml
    1614  Defl:N     1619  -0% 05-11-2018 16:32 44d2eaf3  jj925bx9565/v0001/manifests/manifestInventory.xml
    3118  Defl:N     3123  -0% 05-11-2018 16:32 17bf12ff  jj925bx9565/v0001/manifests/signatureCatalog.xml
    3455  Defl:N     3460  -0% 05-11-2018 16:32 c79865fb  jj925bx9565/v0001/manifests/versionAdditions.xml
    3527  Defl:N     3532  -0% 05-11-2018 16:32 7e525d93  jj925bx9565/v0001/manifests/versionInventory.xml
--------          -------  ---                            -------
 6536623          6537683   0%                            20 files
```

Specifically, I don't see why `c.default_compression = Zlib::NO_COMPRESSION` isn't enough to prevent the files from being mildly deflated (`Defl:N`).

**Comment by atz** [comment] 2018-05-12 00:30
Ok, I tracked down underneath everything where `Zip::Entry` is not honoring the default compression specified in `Zip.default_compression`, but this experience suggests that rubyzip is unlikely to be the way to go.

**Comment by jmartin-sul** [comment] 2018-05-12 00:56
@atz, i would agree, that does not instill confidence in rubyzip

**Comment by hainesr** [comment] 2018-05-13 15:25
I've had a look into this and I think RubyZip is working correctly, but it doesn't make it easy to add files using Store, rather than Deflate.

More details, and my working, here: https://github.com/rubyzip/rubyzip/issues/286#issuecomment-388631440

I've forced files to be Stored using RubyZip by using `Zip::OutputStream` directly, rather than `Zip::File.add`: https://github.com/myGrid/ruby-zip-container/blob/master/lib/zip-container/file.rb#L79

**Comment by julik** [comment] 2018-05-13 18:48
👋 hi folk! Noticed this via the rubyzip issue - but maybe we could help? https://github.com/WeTransfer/zip_tricks

**Comment by atz** [comment] 2018-05-14 17:30
Thanks @hainesr and @julik.  From our perspective, setting `Zip.default_compression = Zlib::NO_COMPRESSION` should result in uncompressed files, the equivalent of the `-0` CLI option.  Alternatively, some other "top level" setting could be provided.

We are working on long term archival storage (think *decades*), so repeatability and predictability are paramount.

**Comment by julik** [comment] 2018-05-14 17:40
What you are after is the "stored" mode, which is not a zlib compression level but just a "verbatim copy" of the file into the ZIP. For this to work the right storage mode has to be set in the entry headers, and the ZIP library has to simply copy the file bytes into the ZIP as is, without passing them through a deflater. ZipTricks supports this usage natively via `write_stored_file` and the related family of functions. We do guarantee byte-for-byte identical output if you manually pass modification dates, but we might be missing some options for things like UNIX permissions - simply because we didn't need them much.

We also explicitly try to support the widest array of (also relatively old) unarchiving applications and we support the EFS entry name flag for all filenames that go beyond basic ASCII.

**Comment by hainesr** [comment] 2018-05-14 18:42
Setting `Zip.default_compression = Zlib::NO_COMPRESSION` does result in uncompressed files. But they have been converted into Deflate format with no compression, so they come out a bit bigger. This behaviour is provided directly by `Zlib` itself and so is not what you want. As @julik says, you need Stored mode. Have you tried using `Zip::OutputStream` to achieve this as per my comment above?

(FWIW I agree that there is a simple API call missing in rubyzip for this, but as I'm not a maintainer I can't just add one - I do think this would be useful though, so I'll work up a PR for this at some point.)

**Comment by jmartin-sul** [comment] 2018-05-23 17:42
the current consensus is that we'll shell out, and capture some provenance info about how the zip was created.  closing for now...

**Closed** 2018-05-23 17:41 UTC
Labels: blocking!, high priority, in progress, replication
