### ISSUE TITLE
send notable events to the dor-services-app event log

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1351] opened 2020-02-04 18:45 UTC
DSA has a newly added event log, intended to centrally record a history of notable things that have happened to an object across various services.  there's a controller method to add events (and likely a wrapper method in dor-services-client, but i could not quickly find that via cursory github search):  https://github.com/sul-dlss/dor-services-app/blob/master/app/controllers/events_controller.rb

we should have notable preservation events sent to this log.  as a start, maybe we log:
- [ ] whatever we're logging via the `AuditResults` class
- [ ] whatever we're manually sending to honeybadger

**Comment by ndushay** [comment] 2020-02-13 23:00
possible duplicate of #1357

**Closed** 2020-02-21 09:50 UTC
