### ISSUE TITLE
(R) Zip Storage (blocking #707)

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#706] opened 2018-04-30 20:57 UTC
- In progress by julian?
- is an NFS mount 
- pres cat config tells you path to the mount (settings.yml)

- What needs what access? (read/write) (in the mount)
  - zip maker worker definetely needs read/write
  - endpoint upload worker definitely needs read access.  if endpoint worker does a touch to indicate recent usage of a zip, it may need write access too.

- this corresponds to the cylinder in the middle of the diagram.

https://www.lucidchart.com/documents/view/45ded815-9fec-46fa-b935-1e26f3819f0e/0

**Comment by jmartin-sul** [comment] 2018-05-01 19:36
closing as a dupe of #678

**Closed by jmartin-sul** 2018-05-01 19:36 UTC
Labels: blocking!, high priority, ready, replication
