### ISSUE TITLE
from dashboard:  ZippedMoabVersion replication counts > PreservedObject versions.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#2145] opened 2023-01-05 00:51 UTC
It's disturbing that the ZippedMoabVersion replication counts are higher then the PreservedObject version counts -- this seems wrong.  

![image](https://user-images.githubusercontent.com/96775/210676873-43dd9653-7c2f-4a3e-a0e8-b9e75930640b.png)

Actions for this ticket:
- [x] ensure what the code is doing is getting the counts as advertised by the column names
- [ ] determine how to fix the bad data (e.g. if the counts are correct, then find the extra replication data ... I think its supposed to be unique by version ...?)

**Comment by ndushay** [comment] 2023-01-11 22:12
Thanks for looking into this!

Given that replication is supposed to be kicked off ONLY by actually updating the version of PreservedObject and/or MoabRecord (see https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow).   So having a zip_max_version that is HIGHER than the preervation_catalog current version is troubing.  

For good measure, I did this:

```
3.0.0 :001 > druids = %w[cw901bh8159 fk847cz0044 gq393sx1578 mg599hw5271 py880rz2144]
 => ["cw901bh8159", "fk847cz0044", "gq393sx1578", "mg599hw5271", "py880rz2144"] 
3.0.0 :002 > druids.each do |druid| 
3.0.0 :003 >   po = PreservedObject.find_by(druid: druid)
3.0.0 :004 >   mr = MoabRecord.find_by(preserved_object: po)
3.0.0 :005 >   puts "#{druid}: #{po.current_version} #{mr.version}"
3.0.0 :006 > end
cw901bh8159: 4 4
fk847cz0044: 3 3
gq393sx1578: 6 6
mg599hw5271: 2 2
py880rz2144: 2 2
```

Have you tried running Audit::ReplicationSupport.zip_part_debug_info  on these 5 druids?  (i just saw that in https://github.com/sul-dlss/preservation_catalog/wiki/Replication-errors )



For case 1 - how is this possible?  I guess if they are expunged _versions_ then perhaps the current_version value wasnt updated as part of that?  @andrewjbtw any insights?    I wonder, e.g., if 3 is the correct version for f847cz0044, if versions 4-8 should be 
- ZipParts removed from db for these versions
- ZipMoabVersion removed fro db
- ask ops to remove whatever exists at endpoints for these versions

I completely defer to @jmartin-sul and @andrewjbtw tho.



For case 2 - I concur that kicking off replication for those 2 objects would be the right thing.  Follow instructions here: https://github.com/sul-dlss/preservation_catalog/wiki/Replication-errors  to proceed with backfilling???

**Comment by ndushay** [comment] 2023-01-11 22:12
this may be worth a huddle;  I think John and Andrew and Ed are required and I am optional.

**Comment by julianmorley** [comment] 2023-01-12 19:09
More fuel to this particular fire.
I did an audit back in Nov'18 and found this:

```
py880rz2144 – v1 thru v4 exist and are legit. Versions 5,6,7,8 and 9 have been deleted.
mg599hw5271 – v1 thru v4 exist and are legit. Versions 5,6,7 and 8 have been deleted.
```
So, as of Nov'18, these druids had 4 versions. Worth a check that they should still have 4 versions, and this is a case of them just needing replication again.

I'd also be just a little bit suspicious of these druids to verify that the versions 1 and 2 on disk actually match versions 1 and 2 on the cloud endpoints, just in case they were deleted and re-created and we have the *old* versions in the cloud.

**Comment by edsu** [comment] 2023-01-17 18:43
So it sounds like we can maybe close this issue since the Dashboard is working as designed? But maybe we need issues to deal with the cleanup if there isn't one already?

**Comment by ndushay** [comment] 2023-01-17 19:45
That sounds right, ed.  Would you write the tickets for the cleanup and then close this one?

**Comment by justinlittman** [comment] 2023-01-31 13:26
Remediation completed. See also https://github.com/sul-dlss/operations-tasks/issues/3280

**Closed by justinlittman** 2023-01-31 13:26 UTC
