### ISSUE TITLE
ZipParts using bad S3 key -- MoabReplicationAudit (correctly) marking zip_parts as checksum mismatch error

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1088] opened 2018-09-02 18:33 UTC
Every zip_part checked so far has been flagged with zip_parts.status = 3 (checksum mismatch).

**Comment by tallenaz** [comment] 2018-09-17 23:52
Talked this over with @SaravShah and we have two ideas for why this might be happening: (1) these objects were replicated before we changed the zip command, so running them through replication again would correct the mismatch, or (2) some bug in how the zip part checksums are created. Will investigate the former.

**Comment by tallenaz** [comment] 2018-09-18 17:41
When I try re-replicating one of these objects, it gets all the way through to an S3WestDeliveryJob enqueued that appears not to finish.

**Comment by julianmorley** [comment] 2018-09-19 21:52
This druid exists on us-west-2...
```
[jmorley@preservation-catalog-prod-03 ~]$ aws s3api --profile us_west_2 head-object --bucket sul-sdr-aws-us-west-2-archive --key bb/020/ng/8351/bb020ng8351.v0001.zip
{
    "AcceptRanges": "bytes",
    "ContentType": "",
    "LastModified": "Wed, 29 Aug 2018 04:05:23 GMT",
    "ContentLength": 55800503,
    "ETag": "\"0b6548a89aaff7c3e6ef582ab60669ee-11\"",
    "StorageClass": "GLACIER",
    "Metadata": {
        "size": "55800503",
        "parts_count": "1",
        "zip_version": "Zip 3.0 (July 5th 2008)",
        "checksum_md5": "92588b415778641dbce263e74bed5a21",
        "zip_cmd": "zip -r0X -s 10g /sdr-transfers/bb/020/ng/8351/bb020ng8351.v0001.zip bb020ng8351/v0001"
    }
}
```
Database includes 2 records for this file, both wrong - one status 1 (not present on us-east-1) and the other status 3 (md5 mismatch):
```
pres=# select * from zip_parts where md5='92588b415778641dbce263e74bed5a21'
;
   id    |   size   | zipped_moab_version_id |         created_at         |         updated_at         |               md5                |                                                                 create_info
                                                                  | parts_count | suffix | status |    last_existence_check    |  last_checksum_validation  
---------+----------+------------------------+----------------------------+----------------------------+----------------------------------+----------------------------------------------------------------------------
------------------------------------------------------------------+-------------+--------+--------+----------------------------+----------------------------
 7787732 | 55800503 |                7832465 | 2018-08-29 04:05:18.977614 | 2018-08-29 04:05:18.977614 | 92588b415778641dbce263e74bed5a21 | {:zip_cmd=>"zip -r0X -s 10g /sdr-transfers/bb/020/ng/8351/bb020ng8351.v0001
.zip bb020ng8351/v0001", :zip_version=>"Zip 3.0 (July 5th 2008)"} |           1 | .zip   |      1 |                            | 
 7787735 | 55800503 |                7832464 | 2018-08-29 04:05:18.992429 | 2018-09-19 07:00:31.105885 | 92588b415778641dbce263e74bed5a21 | {:zip_cmd=>"zip -r0X -s 10g /sdr-transfers/bb/020/ng/8351/bb020ng8351.v0001
.zip bb020ng8351/v0001", :zip_version=>"Zip 3.0 (July 5th 2008)"} |           1 | .zip   |      3 | 2018-09-19 07:00:31.060819 | 2018-09-19 07:00:31.104764
(2 rows)
```

**Comment by tallenaz** [comment] 2018-09-19 23:27
The `size` and `zip_cmd` is also different. Compare:
```
"Metadata": {
        "size": "55800503",
        "parts_count": "1",
        "zip_version": "Zip 3.0 (July 5th 2008)",
        "checksum_md5": "92588b415778641dbce263e74bed5a21",
        "zip_cmd": "zip -r0X -s 10g /sdr-transfers/bb/020/ng/8351/bb020ng8351.v0001.zip bb020ng8351/v0001"
    }
```
```
[26] pry(main)> aws_s3_object.metadata
=> {"zip_cmd"=>"zip -r0X -s 10g /sdr-transfers/bb/020/ng/8351/bb020ng8351.v0004.zip bb020ng8351/v0004",
 "checksum_md5"=>"ee9115bea2b04d1db0046eaee2dd0f70",
 "zip_version"=>"Zip 3.0 (July 5th 2008)",
 "parts_count"=>"1",
 "size"=>"55266"}
```

**Comment by jmartin-sul** [comment] 2018-10-08 23:05
we're just now getting back to working on this, but...

in pairing a few weeks ago, @tallenaz and i discovered some incorrect code here:
https://github.com/sul-dlss/preservation_catalog/blob/5876ed4750aaea7de067e1841a85b67208836ef6/app/models/zip_part.rb#L39-L41

note that it is using `complete_moab.version` to generate the s3_key for the zip part.  however, `version` on `CompleteMoab` is the current latest version of the entire moab on disk, and so will always be the latest version.  however, for the `s3_key`, we want the key to use the version for the `ZipPart`'s parent `ZippedMoabVersion`.

e.g., with the current buggy code, a moab which is currently at version 3 would use `v0003` in all of the S3 keys for all its parts, including the parts associated with ZMVs and zip parts for versions 1 and 2.  the manual investigation that tony and i did with some example parts from the rails console on prod provided empirical validation of this theory.

the fix for that is simple:  we should instead use `zipped_moab_version.version`, which will be the version number specific to the ZMV for which parts are being generated and shipped off.  we've also added tests that cover the specific bug caused by our original oversight.

since we've pushed up lots of content under the wrong s3 key, this will require some remediation (except for objects that only have a single version, which aren't affected by this bug).

i've changed the title to reflect our current understanding.

**Comment by jmartin-sul** [comment] 2018-10-08 23:08
we will file a new ticket for remediation

**Comment by jmartin-sul** [comment] 2018-10-10 00:54
reopening, as it seems the fix in #1097 was necessary, but not sufficient.

things work fine now when the audit check is run inline using `perform_now` from rails console on prod.  however, when the audit check is run by the worker asynchronously (using `perform_later`), the same part that passed the inline audit check will be set to `checksum_mismatch`.

we are stumped at the moment, and will do some more investigation.  @atz suggests that we start by writing a failing test, i.e. trying to reproduce locally in specs using the resque backend.

**Comment by atz** [comment] 2018-10-10 19:10
We had stale workers still running the old code.  Once refreshed, verified correct behavior.  Close?

**Comment by jmartin-sul** [comment] 2018-10-10 20:05
yup, closing...

**Closed by jmartin-sul** 2018-10-10 20:05 UTC
Labels: bug, high priority, needs review
