### ISSUE TITLE
New Moabs not automatically registered in catalog, thus  not automatically replicating

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1094] opened 2018-09-19 17:19 UTC
The list of druids that do not have replicated zip parts on us-west-2 is > 6,000, the vast majority of which are druids first seen by presCat on either Wednesday Sept 5th or Wednesday Sept 12th. Why did these druids not get replicated on creation/discovery?

Random chunk of example druids:
```
pd312gn8909
vc108cn2131 
yx370hn9514
wj767wd4488
pm989fn5823
bx715my3000 
ng227jd7748 
sq121sf4011 
pf272hs0466
rz124ms5123
jh300fx3734 
yd708zd1878
```
Expectation: within 48 hours of a new druid being detected, or a new version of a druid being created, that druid should be fully replicated to us-west-2.

**Comment by julianmorley** [comment] 2018-10-11 21:09
```
bb245xr3174,1
bb577dn5119,1
br175sm2382,1
bt229xb1628,1
by113dm6633,1
cc652gf3760,1
cd668ht2605,1
cd888qz7910,1
cf122fq7244,1
cg137ht2403,1
cj021dm1729,1
cj926ks0007,1
ck152nk0140,1
cp407vf6483,1
cp534sy3807,1
cv130sm3463,1
cx408sp6690,1
dc729cv1052,1
dd154ww2950,1
df057ts1262,1
dg596yw2899,1
dh149bj2588,1
dk162jk4831,1
dp421cx5590,1
dt761qn3067,1
dw544wq3021,1
dx193wp5921,1
fc005jk6219,1
ff412bq2639,1
fg667tb8114,1
fj959gw5989,1
fn300sh4695,1
ft420jq6278,1
ft463cr7324,1
fv680zn0551,1
gc382kr2367,1
gc447wg4670,1
gd075bv7412,1
gf105hx7744,1
gf992mq0001,1
gf992nq7496,1
gh175fw6182,1
gj165cj4832,1
gj301fr4400,1
gk775mf2152,1
gp049gy4581,1
gs558rw3970,1
gw378by3142,1
gx789xx9626,1
gy770kq9371,1
hb483bk0370,1
hc707fn1210,1
hd500tn8363,1
hf372gp2031,1
hg418cj6884,1
hg745mw6106,1
hj315rt9106,1
hk436nj5214,1
hn779dz5276,1
hq433bc4750,1
jc606bd1837,1
jc705rv5462,1
jk397zm0589,1
jk986db2034,1
jp024hs8247,1
jq855pf7139,1
jr019yf7447,1
js292ct0416,1
js638fm5840,1
kd197bt6275,1
kd400nk4237,1
kd571wg2684,1
kf241tx1425,1
kg157dw7107,1
kg377ym9533,1
kh031vb3784,1
kh498hs2585,1
kj240vx5850,1
kn708jy1067,1
kn838sr1425,1
kp307cf6540,1
kq583cf5024,1
ks708rh0077,1
kt697gw8793,1
kv788dx0157,1
kw646vn7507,1
ky904tq4761,1
mc608ds3246,1
mk049fh5879,1
mn853pr5254,1
mt831fp4107,1
my836kr2743,1
mz632hc5335,1
nb064cy0956,1
nd704fg0701,1
ng662hp9543,1
ng996hs7776,1
nj149sq4371,1
np651nq9061,1
np709vp1709,1
nq351zk2893,1
```

**Comment by julianmorley** [comment] 2018-10-12 17:57
Also documenting how to manually register druid-versions with the catalog would be nice.

**Comment by jmartin-sul** [comment] 2018-10-12 18:04
clarification from @julianmorley in standup this morning:  it's not just that the druids aren't being replicated, it's that they're not registering in the catalog in the first place (and so of course, it never knows to replicate them).  there is, however, a moab on disk for these druids.

questions:
* once in the catalog, is it replicable?
* anything in the logs?  m2c logs?  robot logs?
* do we get any errors when we manually M2C the druid to get it into the catalog?
* any commonality in these druids?  where are they coming from?  dropped robot calls?

**Comment by jmartin-sul** [comment] 2018-10-12 19:16
@julianmorley, if you'd like to manually M2C a druid, you can do so by opening rails console and calling
```ruby
Audit::MoabToCatalog.check_existence_for_druid('jj925bx9565')
```

see:  https://github.com/sul-dlss/preservation_catalog#moab-to-catalog-m2c-existenceversion-check

you can manually queue it for CV, or let the scheduled CV queue population load it for checking based on checksum TTL.  once it's fully validated, you can queue it for replication by calling `replicate!` on each of its `zipped_moab_versions`.


after some debugging with @tallenaz and @SaravShah, it appears that the problem is that robots requests are not making it to pres cat.  we moved the pres cat VMs to different IPs, and then needed to configure shib to allow request from robots through again.  once that was done, robot machines appeared to be able to hit pres cat again.  additionally, manual registration of the moab in the catalog as described above worked, and manual triggering of CV audit and replication also appeared to succeed once the druid was registered in pres cat.

**Comment by jmartin-sul** [comment] 2018-10-12 19:18
also, FWIW, every druid in the description's example druid list is now in the catalog, which implies to me that M2C is in fact working, unless someone went and manually registered them.

**Comment by jmartin-sul** [comment] 2018-10-12 19:33
manually triggered M2C just now.  if the druids julian listed yesterday are all registered once the M2C queue is clear, i think we can call this issue closed?  we'll have a backlog of stuff to replicate, but we've got tools and procedures for dealing with that, already in use.

**Comment by jmartin-sul** [comment] 2018-10-13 15:40
M2C from yesterday has completed.

if i open a rails console on prod, and put all the druids @julianmorley lists in his list comment in a var called `druid_list`, i can query the `complete_moabs` table and all appears to be well (the `ok` status indicates they've all passed checksum validation):
```ruby
[40] pry(main)> CompleteMoab.by_druid(druid_list).group(:status).count
=> {"ok"=>101}
[41] pry(main)> 
```

turns out the aggregate size of that druid list is small relative to our zip making temp space (which currently has 9.3 TB free):
```ruby
[73] pry(main)> include ActionView::Helpers::NumberHelper
=> Object
[74] pry(main)> 
[75] pry(main)> CompleteMoab.by_druid(druid_list).sum(:size)
=> 0.25994537751e11
[76] pry(main)> 
[77] pry(main)> number_to_human_size(CompleteMoab.by_druid(druid_list).sum(:size))
=> "24.2 GB"
[78] pry(main)> 
```

so i went ahead and triggered replication for those druids as described in one of my comments above:
```ruby
CompleteMoab.by_druid(druid_list).find_each(&:create_zipped_moab_versions!)
ZippedMoabVersion.by_druid(druid_list).find_each(&:replicate!)
```

a quick glance at the resque dashboard shows zips being made and delivered.

so, considering that robots seem to be talking to the catalog again, and M2C appears to be catching it up, and things are getting CVed and replicating fine once they're `ok`... i think we can probably close this?

**Closed** 2018-10-13 15:54 UTC
Labels: bug, high priority, in progress
