### ISSUE TITLE
zip segment names are being incorrectly generated(?)

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1095] opened 2018-09-26 19:15 UTC
Consider druid vb008fc5700

AWS S3 bucket contains the following files for this druid:
```
vb/008/fc/5700/vb008fc5700.v0001.z01
vb/008/fc/5700/vb008fc5700.v0001.z05
vb/008/fc/5700/vb008fc5700.v0001.z06
vb/008/fc/5700/vb008fc5700.v0001.z07
vb/008/fc/5700/vb008fc5700.v0001.z08
vb/008/fc/5700/vb008fc5700.v0001.z09
vb/008/fc/5700/vb008fc5700.v0001.z10
vb/008/fc/5700/vb008fc5700.v0001.z11
vb/008/fc/5700/vb008fc5700.v0001.z12
vb/008/fc/5700/vb008fc5700.v0001.z13
vb/008/fc/5700/vb008fc5700.v0001.z14
vb/008/fc/5700/vb008fc5700.v0001.z15
vb/008/fc/5700/vb008fc5700.v0001.z16
vb/008/fc/5700/vb008fc5700.v0001.z17
vb/008/fc/5700/vb008fc5700.v0001.z18
vb/008/fc/5700/vb008fc5700.v0001.z19
vb/008/fc/5700/vb008fc5700.v0001.z20
vb/008/fc/5700/vb008fc5700.v0001.z21
vb/008/fc/5700/vb008fc5700.v0001.z22
vb/008/fc/5700/vb008fc5700.v0001.z23
vb/008/fc/5700/vb008fc5700.v0001.z26
vb/008/fc/5700/vb008fc5700.v0001.z27
vb/008/fc/5700/vb008fc5700.v0001.z28
vb/008/fc/5700/vb008fc5700.v0001.z29
vb/008/fc/5700/vb008fc5700.v0001.zip
vb/008/fc/5700/vb008fc5700.v0002.zip
```

Note: missing order (z02, z03 and z04) and a total of 27 uploaded segments for version 1.

Metadata for the upload says:
```
{
    "AcceptRanges": "bytes", 
    "ContentType": "", 
    "LastModified": "Mon, 17 Sep 2018 10:08:05 GMT", 
    "ContentLength": 7405818770, 
    "ETag": "\"b024db8b693879360086f845c0dbcb8d-1413\"", 
    "StorageClass": "GLACIER", 
    "Metadata": {
        "size": "7405818770", 
        "parts_count": "27", 
        "zip_version": "Zip 3.0 (July 5th 2008)", 
        "checksum_md5": "e2d64ef108bfd463c8cf71478063c7f7", 
        "zip_cmd": "zip -r0X -s 10g /sdr-transfers/vb/008/fc/5700/vb008fc5700.v0001.zip vb008fc5700/v0001"
    }
}
```
Note parts_count: 27, which implies the final segment should be z26, *not* z29.
There are 3 unexpected segments present: z27, z28 and z29.
There are 3 expected segments missing: z02, z03, z04.
This *suggests* that the unexpected segments are, in fact, the missing z02, z03 and z04. But even if that is the case, this is broken.

**Comment by julianmorley** [comment] 2018-09-26 19:20
Oh - and I missed that z24 and z25 are also missing from AWS, but I suspect that's explained by an incomplete upload.

**Comment by julianmorley** [comment] 2018-10-01 17:08
Another problem archive: fk204hs8349 version 1
It's zip_parts says it should have 48 parts, but there are 54 zip segments uploaded. The actual volume size supports the 54 zip parts claim - v0001 (disk13) is 548GB = 55 parts, z01 thru z54 plus .zip. So it looks like zip_parts counted/calculated wrong.

```
[dlss-jmorley:~/tcr ]$ ../audit2/list_druid_keys.sh fk204hs8349
fk/204/hs/8349/fk204hs8349.v0001.z01
fk/204/hs/8349/fk204hs8349.v0001.z02
fk/204/hs/8349/fk204hs8349.v0001.z03
fk/204/hs/8349/fk204hs8349.v0001.z04
fk/204/hs/8349/fk204hs8349.v0001.z05
fk/204/hs/8349/fk204hs8349.v0001.z06
fk/204/hs/8349/fk204hs8349.v0001.z07
fk/204/hs/8349/fk204hs8349.v0001.z08
fk/204/hs/8349/fk204hs8349.v0001.z09
fk/204/hs/8349/fk204hs8349.v0001.z10
fk/204/hs/8349/fk204hs8349.v0001.z11
fk/204/hs/8349/fk204hs8349.v0001.z12
fk/204/hs/8349/fk204hs8349.v0001.z13
fk/204/hs/8349/fk204hs8349.v0001.z14
fk/204/hs/8349/fk204hs8349.v0001.z15
fk/204/hs/8349/fk204hs8349.v0001.z16
fk/204/hs/8349/fk204hs8349.v0001.z17
fk/204/hs/8349/fk204hs8349.v0001.z18
fk/204/hs/8349/fk204hs8349.v0001.z19
fk/204/hs/8349/fk204hs8349.v0001.z20
fk/204/hs/8349/fk204hs8349.v0001.z21
fk/204/hs/8349/fk204hs8349.v0001.z22
fk/204/hs/8349/fk204hs8349.v0001.z23
fk/204/hs/8349/fk204hs8349.v0001.z24
fk/204/hs/8349/fk204hs8349.v0001.z25
fk/204/hs/8349/fk204hs8349.v0001.z26
fk/204/hs/8349/fk204hs8349.v0001.z27
fk/204/hs/8349/fk204hs8349.v0001.z28
fk/204/hs/8349/fk204hs8349.v0001.z29
fk/204/hs/8349/fk204hs8349.v0001.z30
fk/204/hs/8349/fk204hs8349.v0001.z31
fk/204/hs/8349/fk204hs8349.v0001.z32
fk/204/hs/8349/fk204hs8349.v0001.z33
fk/204/hs/8349/fk204hs8349.v0001.z34
fk/204/hs/8349/fk204hs8349.v0001.z35
fk/204/hs/8349/fk204hs8349.v0001.z36
fk/204/hs/8349/fk204hs8349.v0001.z37
fk/204/hs/8349/fk204hs8349.v0001.z38
fk/204/hs/8349/fk204hs8349.v0001.z39
fk/204/hs/8349/fk204hs8349.v0001.z40
fk/204/hs/8349/fk204hs8349.v0001.z41
fk/204/hs/8349/fk204hs8349.v0001.z42
fk/204/hs/8349/fk204hs8349.v0001.z43
fk/204/hs/8349/fk204hs8349.v0001.z44
fk/204/hs/8349/fk204hs8349.v0001.z45
fk/204/hs/8349/fk204hs8349.v0001.z46
fk/204/hs/8349/fk204hs8349.v0001.z47
fk/204/hs/8349/fk204hs8349.v0001.z48
fk/204/hs/8349/fk204hs8349.v0001.z49
fk/204/hs/8349/fk204hs8349.v0001.z50
fk/204/hs/8349/fk204hs8349.v0001.z51
fk/204/hs/8349/fk204hs8349.v0001.z52
fk/204/hs/8349/fk204hs8349.v0001.z53
fk/204/hs/8349/fk204hs8349.v0001.z54
fk/204/hs/8349/fk204hs8349.v0001.zip
fk/204/hs/8349/fk204hs8349.v0002.zip
```

**Comment by jmartin-sul** [comment] 2018-10-09 00:57
we've done some investigation, but we'd like to wipe this druid's S3 objects, and see if we can reproduce the error when pushing the druid through the queue using supported means (i.e. `CompleteMoab#create_zipped_moab_versions!` for the whole thing, or `ZippedMoabVersion#replicate!` for a single version).  we'd also like to wait till #1097 (the fix for #1088) is merged and deployed to prod, just to be sure that there's no interplay between that issue and this issue (we doubt there is, but we can imagine how there might be).

as a first pass at debugging/reproducing, we've queued up `fk204hs8349` for zipping, and are waiting to see how many parts are generated, and whether they are pushed to S3.

**Comment by atz** [comment] 2018-10-09 02:45
Code created all 55 files:
```
fk204hs8349.v0001.z01
fk204hs8349.v0001.z02
fk204hs8349.v0001.z03
fk204hs8349.v0001.z04
fk204hs8349.v0001.z05
fk204hs8349.v0001.z06
fk204hs8349.v0001.z07
fk204hs8349.v0001.z08
fk204hs8349.v0001.z09
fk204hs8349.v0001.z10
fk204hs8349.v0001.z11
fk204hs8349.v0001.z12
fk204hs8349.v0001.z13
fk204hs8349.v0001.z14
fk204hs8349.v0001.z15
fk204hs8349.v0001.z16
fk204hs8349.v0001.z17
fk204hs8349.v0001.z18
fk204hs8349.v0001.z19
fk204hs8349.v0001.z20
fk204hs8349.v0001.z21
fk204hs8349.v0001.z22
fk204hs8349.v0001.z23
fk204hs8349.v0001.z24
fk204hs8349.v0001.z25
fk204hs8349.v0001.z26
fk204hs8349.v0001.z27
fk204hs8349.v0001.z28
fk204hs8349.v0001.z29
fk204hs8349.v0001.z30
fk204hs8349.v0001.z31
fk204hs8349.v0001.z32
fk204hs8349.v0001.z33
fk204hs8349.v0001.z34
fk204hs8349.v0001.z35
fk204hs8349.v0001.z36
fk204hs8349.v0001.z37
fk204hs8349.v0001.z38
fk204hs8349.v0001.z39
fk204hs8349.v0001.z40
fk204hs8349.v0001.z41
fk204hs8349.v0001.z42
fk204hs8349.v0001.z43
fk204hs8349.v0001.z44
fk204hs8349.v0001.z45
fk204hs8349.v0001.z46
fk204hs8349.v0001.z47
fk204hs8349.v0001.z48
fk204hs8349.v0001.z49
fk204hs8349.v0001.z50
fk204hs8349.v0001.z51
fk204hs8349.v0001.z52
fk204hs8349.v0001.z53
fk204hs8349.v0001.z54
fk204hs8349.v0001.zip
```
Plus all 55 accompanying `.md5` files. 

If a single druid/version is uploaded multiple times, and the zip partitioning differs (because `zip` binary changes or whatever), then phantom leftover parts is one **expected** possible outcome.  That is precisely why the `parts_count` had to be included in metadata, so that from a single given S3 object (zip part), the entire set of expected files can be deterministically reconstructed.  I.E., in the scope of reconstituting a zip, any phantom leftover parts should be ignored.  See `DruidVersionZip#expected_part_keys` and `ZipPart#suffixes_in_set`.

**Comment by atz** [comment] 2018-10-09 02:53
If I look in the DB, that PO is missing it's version 1:
```ruby
po = PreservedObject.find_by(druid: 'fk204hs8349')
=> #<PreservedObject:0x000000000693c820
 id: 1186654,
 druid: "fk204hs8349",
 current_version: 2,
 created_at: Tue, 23 Jan 2018 17:51:55 UTC +00:00,
 updated_at: Tue, 23 Jan 2018 17:51:55 UTC +00:00,
 preservation_policy_id: 1>

po.complete_moabs
=> [#<CompleteMoab:0x000000000598fdc8
  id: 1186654,
  version: 2,
  preserved_object_id: 1186654,
  moab_storage_root_id: 12,
  created_at: Tue, 23 Jan 2018 17:51:55 UTC +00:00,
  updated_at: Fri, 05 Oct 2018 10:23:23 UTC +00:00,
  last_moab_validation: Sat, 18 Aug 2018 13:12:09 UTC +00:00,
  last_checksum_validation: Sat, 18 Aug 2018 13:12:09 UTC +00:00,
  size: 585797072425,
  status: "ok",
  last_version_audit: Fri, 05 Oct 2018 10:23:23 UTC +00:00,
  last_archive_audit: nil>]
```

So that is weird.

**Comment by jmartin-sul** [comment] 2018-10-09 06:27
i think what's there is right.  there should be only one `complete_moab` for a given PO, because the cm row represents an entire exploded moab directory structure.  whereas `zipped_moab_versions` has a row for each version.

**Comment by atz** [comment] 2018-10-09 19:15
OK, I follow that, but that makes me confused why it is a `has_many` if there will only be one.  I know we've been through that before, but it's been long enough to have drifted out of memory.

**Comment by atz** [comment] 2018-10-09 19:28
Ah... from the schema, the uniqueness constraint is on:
```
t.index ["preserved_object_id", "moab_storage_root_id", "version"]
```
So the possibility is of getting the same PO from a *different* storage_root.

**Comment by jmartin-sul** [comment] 2018-10-09 19:46
yeah.  in `The Future`, the idea was that we might have multiple "online" exploded directory structure moab storage roots for a given moab.

but of course, we don't have that situation at the moment.

also, we might not want to have `version` be part of that uniqueness constraint?  not sure about that, can't remember what the reasoning was for that part of the uniqueness constraint.

**Comment by atz** [comment] 2018-10-17 00:59
I consider this a non-problem right now.  Code created all 55 parts.  Reopen if you find anything.

**Comment by julianmorley** [comment] 2019-02-17 18:51
We're back!
Druid dc156hp0190. zip_parts says 26, actually uploaded 70. Correct # of zip_parts is 70 (it's 697GB).

**Comment by julianmorley** [comment] 2019-02-17 18:54
I suspect that what happened was, whilst creating the zip_parts, /sdr_transfers ran out of space and prematurely called it at 26 parts. Although how it managed to upload / why it started to upload before everything was ready, I don't know. Could the code not generate zip_parts # until zip has successfully completed, and validate zip_parts count by inspecting actual files on disk?

**Comment by julianmorley** [comment] 2019-02-17 19:21
[bad-zip-parts.log](https://github.com/sul-dlss/preservation_catalog/files/2873303/bad-zip-parts.log)

Check out several different attempts to upload this druid; at one point, it's trying to upload part z46... with a part_count of 26!

**Comment by julianmorley** [comment] 2019-02-17 19:30
Work-around was to delete the archive in S3 that had incorrect metadata, and re-run ZipMaker; ZipMaker is now creating archives with correct metadata.. but I still don't know how it got the wrong zip_parts in the first place.

`I, [2019-02-17T11:27:58.854775 #14093]  INFO -- : [ActiveJob] [S3WestDeliveryJob] [b24a0b58-058d-4bf2-96db-1f882f012bf5] Performing S3WestDeliveryJob (Job ID: b24a0b58-058d-4bf2-96db-1f882f012bf5) from Resque(s3_us_west_2_delivery) with arguments: "dc156hp0190", 1, "dc/156/hp/0190/dc156hp0190.v0001.zip", {:checksum_md5=>"87b983b387c514503eaa53983ab05371", :size=>4526479641, :parts_count=>70, :zip_cmd=>"zip -r0X -s 10g /sdr-transfers/dc/156/hp/0190/dc156hp0190.v0001.zip dc156hp0190/v0001", :zip_version=>"Zip 3.0 (July 5th 2008)"}`

**Comment by julianmorley** [comment] 2019-05-05 18:12
More wrong zip_parts. bz480dy8233 on IBM; .zip reports 30 zip_parts, all other parts report (Correctly!) 118 zip_parts.

`{
    "AcceptRanges": "bytes", 
    "ContentType": "application/zip", 
    "LastModified": "Thu, 11 Apr 2019 16:49:34 GMT", 
    "ContentLength": 5105697261, 
    "ETag": "\"2035a9d03be0b617fbbfcb3afc19cd4b-974\"", 
    "PartsCount": 974, 
    "Metadata": {
        "zip_version": "Zip 3.0 (July 5th 2008)", 
        "parts_count": "30", 
        "size": "5105697261", 
        "checksum_md5": "5252fc3e3ff5235fe5f35dcec1d009e8", 
        "zip_cmd": "zip -r0X -s 10g /sdr-transfers/bz/480/dy/8233/bz480dy8233.v0001.zip bz480dy8233/v0001"
    }
}
`
vs.
`{
    "AcceptRanges": "bytes", 
    "ContentType": "binary/octet-stream", 
    "LastModified": "Sun, 05 May 2019 10:56:45 GMT", 
    "ContentLength": 10737418240, 
    "ETag": "\"38a6233c24f5394148cc0fbb3e524629-2048\"", 
    "PartsCount": 2048, 
    "Metadata": {
        "zip_version": "Zip 3.0 (July 5th 2008)", 
        "parts_count": "118", 
        "size": "10737418240", 
        "checksum_md5": "eb2b886e1fcc702025354b4f08a0e12e", 
        "zip_cmd": "zip -r0X -s 10g /sdr-transfers/bz/480/dy/8233/bz480dy8233.v0001.zip bz480dy8233/v0001"
    }
}
`

This is a problem because an audit pass of an S3 endpoint requires the .zip object to accurately report the number of zip_parts.

I suspect this is caused by the clean-up scripts deleting files from sdr_transfers prematurely, and the code that does the upload is dynamically generating zip_parts every time(?) it uploads a file.

So it goes like this:
- ZipMaker zips up a druid, makes 118 file segments.
- Delivery picks up the druid, starts sending segments to S3. Each time it sends a segment, it counts the total number of segments in the sdr-transfers directory and uses that value (so: it's dynamic).
- At some point whilst processing this, the file cleanup scripts run and decide that 88 files are too old, and delete them.
- Delivery picks up the final .zip segment for upload, dynamically calculates zip_parts and gets 30.

Solution: can ZipMaker pass the actually-created number of zip_parts to Delivery as an argument?

**Comment by ndushay** [comment] 2019-12-02 19:32
We believe this is fixed;  closing.  Please re-open or create a new ticket with a ref to this one if this is still occurring.

**Closed by ndushay** 2019-12-02 19:32 UTC
Labels: bug, high priority

**Comment by jmartin-sul** [comment] 2019-12-02 21:07
ah, i had missed that @julianmorley had found more of these as recently as _this_ august.  @julianmorley, feel free to reopen if you think this will keep coming up.  if your [theory](https://github.com/sul-dlss/preservation_catalog/issues/1095#issuecomment-489449720) is right, maybe we should make zip temp space cleanup smarter?  or just increase the temp space size if possible and then also increase the cleanup timeout?
