### ISSUE TITLE
Resque not correctly deleting keys from Redis after job completion

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1087] opened 2018-09-02 17:55 UTC
Redis has almost 10 million keys in it when Resque says it has 1.1million jobs. Investigation of Redis shows many old keys still present - even from deleted queues. See: https://stackoverflow.com/questions/26057790/redis-key-not-removed-even-after-resque-job-completes-successfully for a similar situation.

Why is this a problem? Because even with an LRU deletion policy, Redis will always expand to the RAM available and always be expiring old keys, when the steady-state of the db should be consuming only 10s of MB or RAM and not require constant pruning.

**Comment by tallenaz** [comment] 2018-10-11 18:18
From conversation with @atz (feel free to correct me here if I got it wrong) in standup this morning, our sense is that redis's expected behavior is for its steady state to hover around the maxmemory setting, and for the lru eviction policy to evict old data to let new data get added in all the same. If the worry is that we want the steady state of redis to be much smaller, in order to be able to handle spikes, our sense is that since it is "just" a key value store, redis should be resilient enough, given our maxmemory and eviction policy. If we can agree on this, we should adjust the nagios check to bring it in line with current maxmemory, and close the ticket.

**Comment by tallenaz** [comment] 2018-10-12 16:57
Resque deletes keys from redis via `resque-lock`. In our `ApplicationJob` class:

```
around_perform do |job, block|
    job.class.around_perform_lock(*job.arguments, &block)
  end
```

then in `resque-lock`:

```
def around_perform_lock(*args)
  begin
    yield
  ensure
    # Always clear the lock when we're done, even if there is an
    # error.
    Resque.redis.del(lock(*args))
  end
end

# Override in your job to control the lock key. It is
# passed the same arguments as `perform`, that is, your job's
# payload.
def lock(*args)
  "lock:#{name}-#{args.to_s}"
end
```

**Comment by tallenaz** [comment] 2018-10-13 00:59
After cleaning out a lot of cruft, and while watching a lot of auditing take place, dbsize is stable at well beneath 75,000 keys, and memory usage too, at around 1GB, well under maxmemory.

**Comment by tallenaz** [comment] 2018-10-15 18:00
dbsize is down to 357 keys (no resque:locks left), and memory usage has remained stable for a few days. Closing this and we'll reopen if it becomes a problem again

**Comment by justinlittman** [comment] 2019-12-09 15:22
```
127.0.0.1:6379> info keyspace
# Keyspace
db0:keys=6565371,expires=0,avg_ttl=0
```

**Comment by justinlittman** [comment] 2019-12-09 16:31
So one observation is that reque-lock is using a serialization of the object (`"resque:lock:CatalogToMoabJob-[#<CompleteMoab id: 507891, version: 1, preserved_object_id: 507891, moab_storage_root_id: 4, created_at: \"2018-01-21 09:38:32\", updated_at: \"2019-11-26 16:38:11\", last_moab_validation: \"2019-11-17 19:22:41\", last_checksum_validation: \"2019-11-17 19:22:41\", size: 710333, status: \"ok\", last_version_audit: \"2019-11-26 16:38:11\", last_archive_audit: \"2019-10-16 13:21:11\">, \"/services-disk05/sdr2objects\"]"`) instead of an ActiveJob global id.

**Comment by justinlittman** [comment] 2019-12-10 15:29
@tallenaz Supposing #1254 addresses the problem, do we need to delete the existing locks?

**Comment by jermnelson** [comment] 2019-12-10 16:03
Another option I noticed is that the Redix `max_memory` configuration variable is not being set either in `https://github.com/sul-dlss/preservation_catalog/blob/master/config/resque.yml` or in Puppet (I think at `https://github.com/sul-dlss/puppet/blob/production/modules/profile/manifests/redis.pp`). Setting `max_memory` to a specific value, like the 10s mb mentioned in the ticket's original text and setting the `maxmemory-policy` to **allkeys-lru** would remove all stale keys relative quickly and not cause the millions of stale keys to persist.

**Comment by tallenaz** [comment] 2019-12-12 18:07
@justinlittman I'll check on this -- we have a procedure to find and delete stale locks.

**Comment by tallenaz** [comment] 2019-12-12 19:06
Stale keys have been cleared out. Currently, nagios says

```
OK: Redis memory usage is 1323MB
```

we'll keep an eye on it to see if any keys accumulate after this change is deployed Monday.

**Closed** 2019-12-18 15:48 UTC
Labels: bug, high priority

**Comment by ndushay** [comment] 2019-12-19 01:08
Possibly related:  conv in dlss-preservation-dev slack channel starting with Julian's message of 3:17pm Wed Dec 18

**Comment by ndushay** [comment] 2019-12-19 01:08
@tallenaz re=open this?  or move it to done?  Or straddle between as it is now?

**Comment by tallenaz** [comment] 2019-12-19 02:12
Redis memory usage is at 2622MB right now, which is still an acceptable threshold to nagios, so I'd say we can leave this closed, unless and until nagios complains again.

**Comment by jmartin-sul** [comment] 2021-06-26 01:17
see also:  https://github.com/sul-dlss/preservation_catalog/issues/1726
