### ISSUE TITLE
[migration MVP] Analyze Existing Audit Errors (old storage roots)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1324] opened 2020-01-22 19:40 UTC
If there are some easy wins for fixing audit errors on storage roots before we migrate, that would be awesome.  Reports of errors should be addressed by issue #1318.

This ticket is about figuring out if any of the existing errors can be easily cleared.  Slightly incestuous relationship with issue #1325 - create process to clear an error.

For example, once a Moab has invalid checksums, it won't run M2C -- does M2C pass?  Is it really just a bad checksum?  Can we figure out the correct checksum and fix it?  Can it be automated?  

Example 2:  if a Moab manifest has the wrong version ... can we figure out the right version and fix it?  Can it be automated?

**Comment by jmartin-sul** [comment] 2020-02-11 18:37
using this as a start to get an idea of what's in a bad status on the various storage roots.  looks like all our known errors are `invalid_checksum` issues, and it looks like a reasonably small number of objects, except on storage root 2, which is worisomely high (i feel vaguely like i've identified this issue in the past):
```ruby
[pres@preservation-catalog-prod-01 current]$ ./bin/rails c -e production
Loading production environment (Rails 6.0.2.1)
[1] pry(main)> CompleteMoab.joins(:preserved_object, :moab_storage_root).where.not(status: 'ok').group(:status, :storage_location).order('complete_moabs.status asc, moab_storage_roots.storage_location asc').pluck('complete_moabs.status, moab_storage_roots.storage_location, count(preserved_objects.druid)')


=> [["invalid_checksum", "/services-disk02/sdr2objects", 506],
 ["invalid_checksum", "/services-disk03/sdr2objects", 1],
 ["invalid_checksum", "/services-disk04/sdr2objects", 1],
 ["invalid_checksum", "/services-disk08/sdr2objects", 3],
 ["invalid_checksum", "/services-disk10/sdr2objects", 2],
 ["invalid_checksum", "/services-disk16/sdr2objects", 2],
 ["invalid_checksum", "/services-disk18/sdr2objects", 3],
 ["invalid_checksum", "/services-disk20/sdr2objects", 1]]
[2] pry(main)> 
```

**Comment by ndushay** [comment] 2020-02-13 01:40
@andrewjbtw do you have any insights into the checksum errors?  any patterns?  It's ok if you don't, just asking.

**Comment by andrewjbtw** [comment] 2020-02-13 20:29
I looked at this one: https://argo.stanford.edu/view/druid:bb593hn2771

The content files match the checksums, but there's no versionMetadata.xml for version 1. That seems to be required to have a valid Moab. 

My suspicion is that:

1. bb593hn2771 started out on storage root 1 (it's still there, as a bag)
2. It was copied to a new storage root and put in a Moab structure so it could be versioned
3. The migration didn't include a versionMetadata.xml for version 1, but this wasn't caught until regular auditing started.

So my guess is that it will turn out that most of the storage root 2 audit failures will have the same issue. 

I need to check if they are on storage root 1, and finally upload my listing of what's on storage root 1. I decided to re-generate that listing with more fields from Solr, but held off because of the indexing issues we ran into at the start of last week. I think that's all resolved now.

**Comment by jmartin-sul** [comment] 2020-02-13 20:37
> So my guess is that it will turn out that most of the storage root 2 audit failures will have the same issue

that would be great!  that sounds like the sort of thing we actually could automate fixing to some degree.  though i'd suggest that automation be in the form of a script for this particular remediation, as opposed to something that lives in prescat forever, since we don't expect to create more objects like this going forward (right?).

**Comment by jmartin-sul** [comment] 2020-02-13 20:40
@andrewjbtw i made you a co-assignee on this issue, since you waded in just now, and since i'd have been likely to pull you in at some point anyway 🙂

**Comment by ndushay** [comment] 2020-02-13 21:10
wow - it would be AWESOME if most of the audit errors for moabs had the same type of failure and the fix wasn't too horrid.

**Comment by jmartin-sul** [comment] 2020-02-22 04:23
504 of the errors seem to fit the profile of some moabs that we discovered (and that i thought we had dealt with) during the initial preservation catalog development work cycle.  see also #636, #848 for some prior discussion involving @blalbrit's description for #636.  in particular:

> For a subset of objects in the repository, v001 of the object predated the use of the versionMetadata datastream. These 554 objects (all ETDs) do not have a versionMetadata.xml file. These objects are currently showing as errors in the auditWF. Even when later versions have been added to these objects with the expected versionMetadata.xml file, the v001 folder is still failing the audit and, therefore, the objects are failing the audit as well.
>
> These objects are not, in fact, in error - at the time they were deposited to SDR2, they were representative of the model.

Since the related tickets are all closed, and since none attempt to summarize the problem or indicate an attempt to remediate it entirely, I'm going to open a new ticket.

I believe this new ticket will address the error that @andrewjbtw describes in https://github.com/sul-dlss/preservation_catalog/issues/1324#issuecomment-585956839, including for example druid `bb593hn2771`.

I think the issue is actually the opposite of what the comment describes, in that the issue seems to be an _extraneous_ data stream file and not a missing one.  Or at least I'm hopeful that's the case, because i think it'd be simpler to deal with.

Per that comment though, all instances of this sort of error are confined to service disk 2, and they account for 504 of the 506 (checksum validation) errors on that storage root.

**Comment by jmartin-sul** [comment] 2020-02-22 19:30
for the other 2 moabs with `invalid_checksum` status on storage root 2, i filed #1394

**Comment by jmartin-sul** [comment] 2020-02-22 20:32
spawned #1395 for one a moab with a unique combination of problems

**Comment by jmartin-sul** [comment] 2020-02-22 20:59
spawned #1396 for documentation.

spawned #1397 for what might be some corrupted DOR metadata.

**Comment by jmartin-sul** [comment] 2020-02-22 21:20
spawned #1398 for a couple moabs with a random grab bag of errors, reminiscent of #1395

**Comment by jmartin-sul** [comment] 2020-02-22 21:40
spawned #1399 for another weird extraneous file issue (fr360kt0172)

**Comment by jmartin-sul** [comment] 2020-02-22 21:52
added druid gh926rx4162 to #1192

**Comment by jmartin-sul** [comment] 2020-02-22 22:26
i believe all 513 currently known errors are now accounted for by these tickets, with more relevant context on each one:

* #1192 (checksum validation failure auditing moab for expunged object fk847cz0044)
* #1394 (extraneous technicalMetadata.xml in a couple moabs on storage root 2?)
* #1393 (extraneous versionMetadata.xml file in v1 of 504 moabs on storage root 2)
* #1395 (preservation copy of vq518cf9512 (service disk 8) has a number of issues)
* #1397 (checksum mismatch on metadata file when auditing zx284xc2961 (services-disk10))
* #1398 (files listed in signatureCatalog.xml have slightly different names from actual content files for mg599hw5271 (service disk 8))
* #1399 (fr360kt0172 seems to have a duplicate content file, maybe as a result of an scp mistake? (services-disk16))

i think that covers analysis of the errors overall, and that we can close this ticket in favor of the documentation ticket (#1396), and the above listed tickets for specific categories of errors.

**Closed by jmartin-sul** 2020-02-22 22:26 UTC
Labels: checksum validation
